# Generated by Django 5.2.5 on 2025-08-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtask',
            old_name='destination',
            new_name='train_name',
        ),
        migrations.RemoveField(
            model_name='bookingtask',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='bookingtask',
            name='journey_date',
        ),
        migrations.RemoveField(
            model_name='bookingtask',
            name='passenger_age',
        ),
        migrations.RemoveField(
            model_name='bookingtask',
            name='passenger_name',
        ),
        migrations.RemoveField(
            model_name='bookingtask',
            name='source',
        ),
        migrations.AddField(
            model_name='bookingtask',
            name='pnr_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bookingtask',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingtask',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
