# Generated by Django 5.2.5 on 2025-08-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_destination_bookingtask_train_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtask',
            name='class_type',
            field=models.CharField(choices=[('SL', 'Sleeper'), ('3A', '3rd AC'), ('2A', '2nd AC'), ('1A', '1st AC')], default='SL', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingtask',
            name='coach_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='bookingtask',
            name='destination_station',
            field=models.CharField(blank=True, default='Unknown Destination', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookingtask',
            name='journey_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingtask',
            name='passenger_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingtask',
            name='passenger_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='bookingtask',
            name='passenger_name',
            field=models.CharField(default='Test Passenger', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingtask',
            name='source_station',
            field=models.CharField(default='Unknown Source', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingtask',
            name='booking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingtask',
            name='train_name',
            field=models.CharField(default='Unknown Train', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingtask',
            name='train_number',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
