# Generated by Django 5.2.5 on 2025-08-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookingtask_class_type_bookingtask_coach_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
