# Generated by Django 5.2.5 on 2025-08-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_bookingtask_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtask',
            name='train_name_number',
            field=models.CharField(default='Unknown Train 00000', help_text='e.g., Rajdhani Express 12345', max_length=120),
        ),
        migrations.AlterField(
            model_name='bookingtask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
