# Generated by Django 5.2.5 on 2025-08-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_bookingtask_train_name_number_alter_bookingtask_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtask',
            name='auto_delete_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingtask',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingtask',
            name='retention_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
