# Generated by Django 5.2.5 on 2025-08-12 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bookingtask_auto_delete_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name_number', models.CharField(default='Unknown Train 00000', help_text='e.g., Rajdhani Express 12345', max_length=120)),
                ('train_number', models.CharField(default='00000', max_length=10)),
                ('train_name', models.CharField(default='Unknown Train', max_length=100)),
                ('source_station', models.CharField(default='Unknown Source', max_length=50)),
                ('destination_station', models.CharField(blank=True, default='Unknown Destination', max_length=50, null=True)),
                ('journey_date', models.DateField(blank=True, null=True)),
                ('passenger_name', models.CharField(default='Test Passenger', max_length=100)),
                ('passenger_age', models.PositiveIntegerField(default=0)),
                ('passenger_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('booking_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Scheduled', max_length=20)),
                ('pnr_number', models.CharField(blank=True, max_length=12, null=True)),
                ('seat_number', models.CharField(blank=True, max_length=10, null=True)),
                ('coach_number', models.CharField(blank=True, max_length=5, null=True)),
                ('class_type', models.CharField(choices=[('SL', 'Sleeper'), ('3A', '3rd AC'), ('2A', '2nd AC'), ('1A', '1st AC')], default='SL', max_length=20)),
                ('ticket_pdf', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('ticket_pdf_url', models.URLField(blank=True, null=True)),
                ('auto_delete_enabled', models.BooleanField(default=True)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BookingTask',
        ),
    ]
