# Generated by Django 5.2.5 on 2025-08-14 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_delete_bookingtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='passenger_age',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='passenger_gender',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='passenger_name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='booking.booking')),
            ],
        ),
    ]
