# Generated by Django 5.2.5 on 2025-08-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_booking_passenger_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='coach_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
