# Generated by Django 5.2.1 on 2026-03-15 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_passenger_coach_number_passenger_seat_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('NET_BANKING', 'Net Banking'), ('WALLET', 'Wallet')], default='UPI', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_expiry', models.CharField(blank=True, max_length=5, null=True)),
                ('card_cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking')),
            ],
        ),
    ]
